# Cross.rs configuration
# https://github.com/cross-rs/cross

[build.env]
passthrough = [
  "DATABASE_URL",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
  "dpkg --add-architecture amd64",
  "apt-get update",
  "apt-get install -y protobuf-compiler",
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture arm64",
  "apt-get update",
  "apt-get install -y protobuf-compiler",
]
